substitutions:
  devicename: pms_sensor
  friendly_name: "Pms Sensor"
  
esphome:
  name: $devicename
  platform: ESP8266
  board: esp8285
  
wifi:
  ssid: "SSID"
  password: "password"


# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

uart:
  tx_pin: GPIO01
  rx_pin: GPIO03
  baud_rate: 9600
  
i2c:
  sda: GPIO14
  scl: GPIO13
  scan: True

sensor:
  - platform: pmsx003
    type: PMSX003
    id: pms
    pm_1_0:
      name: "${friendly_name} PM1.0µm"
      id: pm2_5um
    pm_2_5:
      name: "${friendly_name} PM2.5µm"
    pm_10_0:
      name: "${friendly_name} PM10.0µm"
    
  - platform: bme280
    temperature:
      name: "${friendly_name} Temperature"
      oversampling: 16x
    pressure:
      name: "${friendly_name} Pressure"
    humidity:
      name: "${friendly_name} Humidity"  
    address: 0x76
    update_interval: 60s      
  
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
    
  - platform: uptime
    name: "${friendly_name} Uptime"
    
light:
  - platform: neopixelbus
    method: ESP8266_UART1
    type: GRB
    pin: GPIO02
    num_leds: 1
    id: pixel
    name: "NeoPixel Light"  

interval:
  - interval: 10s
    then:
      - if:
          condition:
            lambda: 'return id(pm2_5um).state > 100;'
          then:
            - logger.log: "The sensor value above 100!"
            - light.turn_on:
                id: pixel
                brightness: 20%
                red: 100%
                green: 0%
                blue: 0%
          else:
            - if:
                condition:
                  lambda: 'return id(pm2_5um).state > 50;'
                then:
                  - logger.log: "The sensor value above 50!"
                  - light.turn_on:
                      id: pixel
                      brightness: 20%
                      red: 100%
                      green: 50%
                      blue: 0%
                else:
                  - logger.log: "The sensor value is below 50!"
                  - light.turn_off: pixel